//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSecond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEDZIOWIE
    {
        public int ID_SEDZI { get; set; }
        public string IMIE_SEDZI { get; set; }
        public string NAZWISKO_SEDZI { get; set; }
    }
}
