//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSecond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPOTKANIA
    {
        public int ID_SPOTKANIA { get; set; }
        public int ID_SEDZI { get; set; }
        public int ID_DRUZYNY { get; set; }
        public int ID_MIASTA { get; set; }
        public int DRU_ID_DRUZYNY { get; set; }
        public Nullable<int> BRAMKI_D1 { get; set; }
        public Nullable<int> BRAMKI_D2 { get; set; }
        public Nullable<System.DateTime> DATA_SPOTKANIA { get; set; }
    }
}
