//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSecond.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DRUZYNY
    {
       
        public int ID_DRUZYNY { get; set; }
        public int ID_MIASTA { get; set; }
        public string NAZWA_DRUZYNY { get; set; }
        public Nullable<decimal> PUNKTY { get; set; }
        public Nullable<decimal> BRAMKI { get; set; }
        public Nullable<decimal> ILOSC_SPOTKAN { get; set; }
    }
}
