//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSecond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIASTA
    {
        public int ID_MIASTA { get; set; }
        public string NAZWA_MIASTA { get; set; }
    }
}
