//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSecond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PILKARZE
    {
        public int ID_PILKARZA { get; set; }
        public Nullable<int> ID_DRUZYNY { get; set; }
        public string IMIE_PILKARZA { get; set; }
        public string NAZWISKO_PILKARZA { get; set; }
        public Nullable<System.DateTime> WIEK_PILKARZA { get; set; }
        public string POZYCJA { get; set; }
        public string NARODOWOSC_PILKARZA { get; set; }
    }
}
